name: go
on:
  push:
  pull_request_target:
    branches: [ "master" ]

jobs:
  build-test:
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20', '1.21.x']
    uses: tenfyzhong/workflows/.github/workflows/go-build-test.yml@main
    with: 
      go-version: ${{matrix.go-version}}

