name: go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20', '1.21.x']
    uses: tenfyzhong/workflows/.github/workflows/go-build-test.yml@go-build-test
    with: 
      go-version: ${{matrix.go-version}}

